// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Architecture.Sample.Expand.Models
{
    public partial class B
    {
        public int Recordid { get; set; }
        public long Aid { get; set; }
        public long Cid { get; set; }

        public C C { set; get; }
    }
}