// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Architecture.Sample.Expand.Models
{
    public partial class C
    {
        public long Sortid { get; set; }
        public string Cname { get; set; }
    }
}