// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Architecture.Sample.Expand.Models
{
    public partial class TestContext : DbContext
    {
        public TestContext()
        {
        }

        public TestContext(DbContextOptions<TestContext> options)
            : base(options)
        {
        }

        public virtual DbSet<A> A { get; set; }
        public virtual DbSet<B> B { get; set; }
        public virtual DbSet<C> C { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<A>(entity =>
            {
                entity.HasKey(e => e.Numericalorder)
                    .HasName("PRIMARY");

                entity.ToTable("a");

                entity.Property(e => e.Numericalorder)
                    .HasColumnName("numericalorder")
                    .HasColumnType("bigint(20)");

                entity.Property(e => e.Aname)
                    .IsRequired()
                    .HasColumnName("aname")
                    .HasColumnType("varchar(256)")
                    .HasCharSet("utf8")
                    .HasCollation("utf8_general_ci");


                entity.HasMany(p => p.B).WithOne().HasForeignKey(p => p.Aid).HasPrincipalKey(p => p.Numericalorder);
            });

            modelBuilder.Entity<B>(entity =>
            {
                entity.HasKey(e => e.Recordid)
                    .HasName("PRIMARY");

                entity.ToTable("b");

                entity.Property(e => e.Recordid)
                    .HasColumnName("recordid")
                    .HasColumnType("int(11)");

                entity.Property(e => e.Aid)
                    .HasColumnName("aid")
                    .HasColumnType("bigint(20)");

                entity.Property(e => e.Cid)
                    .HasColumnName("cid")
                    .HasColumnType("bigint(20)");

                entity.HasOne<C>(p => p.C).WithOne().HasForeignKey<C>(p => p.Sortid).HasPrincipalKey<B>(p => p.Cid);
            });

            modelBuilder.Entity<C>(entity =>
            {
                entity.HasKey(e => e.Sortid)
                    .HasName("PRIMARY");

                entity.ToTable("c");

                entity.Property(e => e.Sortid)
                    .HasColumnName("sortid")
                    .HasColumnType("bigint(20)");

                entity.Property(e => e.Cname)
                    .IsRequired()
                    .HasColumnName("cname")
                    .HasColumnType("varchar(500)")
                    .HasCharSet("utf8")
                    .HasCollation("utf8_general_ci");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}